In [3]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

from mlxtend.frequent_patterns import apriori
from mlxtend.frequent_patterns import association_rules

df = pd.read_csv('datasets/coffee_shop.csv', sep=';')
df.head()

,Id,Coffee,Tea,Hot_chocolate,Cheese,Sausage,Veggie_deli_slices,Cucumber,Tomato,Juice,Milk,Dark_bread,White_bread,Sweet_bun,Croissant,Fruit_chunks,Smoothie
0,1,1.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,2,1.0,NaN,NaN,1.0,1.0,NaN,NaN,NaN,NaN,NaN,NaN,1.0,NaN,NaN,NaN,NaN
2,3,1.0,NaN,NaN,NaN,1.0,NaN,NaN,NaN,NaN,1.0,NaN,1.0,NaN,NaN,NaN,NaN
3,4,NaN,1.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,5,1.0,NaN,NaN,1.0,NaN,NaN,1.0,1.0,NaN,NaN,1.0,NaN,NaN,NaN,NaN,NaN

In [4]:
df.dtypes

Id                      int64
Coffee                float64
Tea                   float64
Hot_chocolate         float64
Cheese                float64
Sausage               float64
Veggie_deli_slices    float64
Cucumber              float64
Tomato                float64
Juice                 float64
Milk                  float64
Dark_bread            float64
White_bread           float64
Sweet_bun             float64
Croissant             float64
Fruit_chunks          float64
Smoothie              float64
dtype: object

In [5]:
df.describe()

,Id,Coffee,Tea,Hot_chocolate,Cheese,Sausage,Veggie_deli_slices,Cucumber,Tomato,Juice,Milk,Dark_bread,White_bread,Sweet_bun,Croissant,Fruit_chunks,Smoothie
count,60.000000,38.0,7.0,9.0,22.0,14.0,14.0,19.0,12.0,7.0,11.0,16.0,7.0,9.0,6.0,8.0,10.0
mean,30.500000,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0
std,17.464249,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
min,1.000000,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0
25%,15.750000,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0
50%,30.500000,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0
75%,45.250000,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0
max,60.000000,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0

In [6]:
df.isnull().sum()

Id                     0
Coffee                22
Tea                   53
Hot_chocolate         51
Cheese                38
Sausage               46
Veggie_deli_slices    46
Cucumber              41
Tomato                48
Juice                 53
Milk                  49
Dark_bread            44
White_bread           53
Sweet_bun             51
Croissant             54
Fruit_chunks          52
Smoothie              50
dtype: int64

In [7]:
# drop id
df = df.drop(columns='Id')
# replace NaN values with False
df = df.fillna(False)
# replace 1.0 values with True
df = df.apply(lambda x: x.map(lambda y: True if y == 1.0 else y))
df

,Coffee,Tea,Hot_chocolate,Cheese,Sausage,Veggie_deli_slices,Cucumber,Tomato,Juice,Milk,Dark_bread,White_bread,Sweet_bun,Croissant,Fruit_chunks,Smoothie
0,True,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False
1,True,False,False,True,True,False,False,False,False,False,False,True,False,False,False,False
2,True,False,False,False,True,False,False,False,False,True,False,True,False,False,False,False
3,False,True,False,False,False,False,False,False,False,False,False,False,False,False,False,False
4,True,False,False,True,False,False,True,True,False,False,True,False,False,False,False,False
5,True,False,False,True,False,False,True,True,False,False,True,False,False,False,False,False
6,False,False,True,True,False,False,True,False,False,False,True,False,False,False,False,False
7,False,False,True,True,False,True,False,False,False,False,True,False,False,False,False,True
8,True,False,False,False,False,False,False,False,False,False,False,False,True,True,False,False
9,False,False,True,False,False,False,False,False,False,False,False,False,True,True,False,False
10,False,False,False,False,False,False,False,False,False,True,False,False,False,False,False,False
11,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False
12,False,False,False,False,False,False,False,False,False,True,False,False,True,False,False,False
13,False,False,True,True,True,False,False,False,False,False,False,True,False,False,False,False
14,True,False,False,False,True,False,False,False,False,True,False,False,True,True,False,False
15,False,True,False,False,False,True,False,False,False,True,False,False,False,False,True,True
16,True,False,False,False,False,False,False,False,False,False,False,False,False,False,True,False
17,True,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False
18,True,False,False,False,False,True,False,False,False,False,False,False,False,False,True,True
19,False,False,False,False,False,True,False,False,False,False,False,False,False,False,False,False
20,True,False,False,False,False,True,True,True,False,False,True,False,False,False,False,True
21,True,False,False,False,False,True,True,False,False,False,True,False,False,False,False,False
22,True,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False
23,False,True,False,False,False,False,True,True,False,False,True,False,False,False,True,False
24,True,False,False,True,False,False,False,False,False,False,False,False,False,False,False,False
25,True,False,False,True,False,False,False,False,False,False,False,False,False,False,False,False
26,True,False,False,True,True,False,True,False,True,False,False,False,False,False,False,False
27,True,False,False,True,True,False,False,False,True,False,False,False,False,False,False,False
28,True,False,False,True,True,False,True,False,True,True,False,False,False,False,False,False
29,True,False,False,False,False,True,True,True,False,False,True,False,False,False,False,True
30,True,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False
31,True,False,False,True,True,False,False,True,False,False,False,True,False,False,False,False
32,True,False,False,False,True,False,False,False,False,True,False,True,False,False,False,False
33,False,True,False,False,False,False,False,False,False,False,False,False,False,False,False,False
34,True,False,False,True,False,False,True,True,False,False,True,False,False,False,False,False
35,True,False,False,True,False,False,True,True,False,False,True,False,False,False,False,False
36,False,False,True,True,False,False,True,False,False,False,True,False,False,False,False,False
37,False,False,True,True,False,True,False,False,False,False,True,False,False,False,False,True
38,True,False,False,False,False,False,False,False,False,False,False,False,True,True,False,False
39,False,False,True,False,False,False,False,False,False,False,False,False,True,True,False,False
40,False,False,False,False,False,False,False,True,False,True,False,False,False,False,False,False
41,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False
42,False,False,False,False,False,False,False,False,False,True,False,False,True,False,False,False
43,False,False,True,True,True,False,True,False,False,False,False,True,False,False,False,False
44,True,False,False,False,True,False,False,False,False,True,False,False,True,True,False,False
45,False,True,False,False,False,True,False,False,False,False,False,False,False,False,True,False
46,True,False,False,False,False,False,False,False,False,False,False,False,False,False,True,False
47,True,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False
48,True,False,True,False,False,True,False,False,True,False,False,False,False,False,True,False
49,False,False,False,False,False,True,False,False,False,False,False,False,False,False,False,True
50,True,False,False,False,False,True,True,True,False,False,True,True,False,False,False,True
51,True,False,False,False,False,True,True,False,False,False,True,False,False,False,False,True
52,True,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False
53,False,True,False,False,True,False,True,True,False,False,True,False,True,False,True,False
54,True,False,False,True,False,False,False,False,False,False,False,False,False,False,False,False
55,True,False,False,True,False,False,False,False,False,False,False,False,False,False,False,False
56,True,False,False,True,True,False,True,False,True,False,False,False,False,False,False,False
57,True,False,False,True,True,False,False,False,True,False,False,False,False,False,False,False
58,True,False,False,True,False,False,True,False,True,True,False,False,False,False,False,False
59,True,True,False,False,False,True,True,True,False,False,True,False,False,False,False,True

In [8]:
frequent_itemsets = apriori(df, min_support=0.1, use_colnames=True)
frequent_itemsets

     support                                           itemsets
0   0.633333                                frozenset({Coffee})
1   0.116667                                   frozenset({Tea})
2   0.150000                         frozenset({Hot_chocolate})
3   0.366667                                frozenset({Cheese})
4   0.233333                               frozenset({Sausage})
5   0.233333                    frozenset({Veggie_deli_slices})
6   0.316667                              frozenset({Cucumber})
7   0.200000                                frozenset({Tomato})
8   0.116667                                 frozenset({Juice})
9   0.183333                                  frozenset({Milk})
10  0.266667                            frozenset({Dark_bread})
11  0.116667                           frozenset({White_bread})
12  0.150000                             frozenset({Sweet_bun})
13  0.100000                             frozenset({Croissant})
14  0.133333                          frozenset({Fruit_chunks})
15  0.166667                              frozenset({Smoothie})
16  0.266667                        frozenset({Coffee, Cheese})
17  0.183333                       frozenset({Coffee, Sausage})
18  0.133333            frozenset({Coffee, Veggie_deli_slices})
19  0.233333                      frozenset({Coffee, Cucumber})
20  0.150000                        frozenset({Tomato, Coffee})
21  0.116667                         frozenset({Coffee, Juice})
22  0.100000                          frozenset({Milk, Coffee})
23  0.166667                    frozenset({Dark_bread, Coffee})
24  0.100000                      frozenset({Smoothie, Coffee})
25  0.100000                 frozenset({Hot_chocolate, Cheese})
26  0.150000                       frozenset({Sausage, Cheese})
27  0.183333                      frozenset({Cucumber, Cheese})
28  0.100000                         frozenset({Juice, Cheese})
29  0.133333                    frozenset({Dark_bread, Cheese})
30  0.100000                  frozenset({Sausage, White_bread})
31  0.100000          frozenset({Veggie_deli_slices, Cucumber})
32  0.133333        frozenset({Dark_bread, Veggie_deli_slices})
33  0.166667          frozenset({Smoothie, Veggie_deli_slices})
34  0.166667                      frozenset({Tomato, Cucumber})
35  0.233333                  frozenset({Dark_bread, Cucumber})
36  0.166667                    frozenset({Dark_bread, Tomato})
37  0.116667                  frozenset({Smoothie, Dark_bread})
38  0.100000                  frozenset({Sweet_bun, Croissant})
39  0.116667               frozenset({Sausage, Coffee, Cheese})
40  0.133333              frozenset({Cucumber, Coffee, Cheese})
41  0.100000                 frozenset({Coffee, Juice, Cheese})
42  0.100000  frozenset({Coffee, Veggie_deli_slices, Cucumber})
43  0.100000  frozenset({Dark_bread, Coffee, Veggie_deli_sli...
44  0.100000  frozenset({Smoothie, Coffee, Veggie_deli_slices})
45  0.133333              frozenset({Tomato, Coffee, Cucumber})
46  0.166667          frozenset({Dark_bread, Coffee, Cucumber})
47  0.133333            frozenset({Dark_bread, Coffee, Tomato})
48  0.100000          frozenset({Dark_bread, Cucumber, Cheese})
49  0.100000  frozenset({Dark_bread, Veggie_deli_slices, Cuc...
50  0.116667  frozenset({Smoothie, Dark_bread, Veggie_deli_s...
51  0.166667          frozenset({Dark_bread, Cucumber, Tomato})
52  0.100000  frozenset({Dark_bread, Coffee, Veggie_deli_sli...
53  0.133333  frozenset({Dark_bread, Coffee, Cucumber, Tomato})

In [10]:
# generate association rules
rules = association_rules(frequent_itemsets, metric='confidence', min_threshold=0.5)
# sort in descending order of confidence
rules = rules.sort_values(by='confidence', ascending=False)
rules

,antecedents,consequents,antecedent support,consequent support,support,confidence,lift,representativity,leverage,conviction,zhangs_metric,jaccard,certainty,kulczynski
71,"frozenset({Dark_bread, Tomato})",frozenset({Cucumber}),0.166667,0.316667,0.166667,1.0,3.157895,1.0,0.113889,inf,0.820000,0.526316,1.000000,0.763158
72,"frozenset({Tomato, Cucumber})",frozenset({Dark_bread}),0.166667,0.266667,0.166667,1.0,3.750000,1.0,0.122222,inf,0.880000,0.625000,1.000000,0.812500
65,"frozenset({Smoothie, Dark_bread})",frozenset({Veggie_deli_slices}),0.116667,0.233333,0.116667,1.0,4.285714,1.0,0.089444,inf,0.867925,0.500000,1.000000,0.750000
79,"frozenset({Coffee, Veggie_deli_slices, Cucumber})",frozenset({Dark_bread}),0.100000,0.266667,0.100000,1.0,3.750000,1.0,0.073333,inf,0.814815,0.375000,1.000000,0.687500
18,frozenset({Smoothie}),frozenset({Veggie_deli_slices}),0.166667,0.233333,0.166667,1.0,4.285714,1.0,0.127778,inf,0.920000,0.714286,1.000000,0.857143
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
33,"frozenset({Coffee, Cheese})",frozenset({Cucumber}),0.266667,0.316667,0.133333,0.5,1.578947,1.0,0.048889,1.366667,0.500000,0.296296,0.268293,0.460526
59,frozenset({Dark_bread}),"frozenset({Tomato, Coffee})",0.266667,0.150000,0.133333,0.5,3.333333,1.0,0.093333,1.700000,0.954545,0.470588,0.411765,0.694444
69,frozenset({Veggie_deli_slices}),"frozenset({Smoothie, Dark_bread})",0.233333,0.116667,0.116667,0.5,4.285714,1.0,0.089444,1.766667,1.000000,0.500000,0.433962,0.750000
31,frozenset({Sausage}),"frozenset({Coffee, Cheese})",0.233333,0.266667,0.116667,0.5,1.875000,1.0,0.054444,1.466667,0.608696,0.304348,0.318182,0.468750
94,frozenset({Dark_bread}),"frozenset({Tomato, Coffee, Cucumber})",0.266667,0.133333,0.133333,0.5,3.750000,1.0,0.097778,1.733333,1.000000,0.500000,0.423077,0.750000

In [11]:
rules = association_rules(frequent_itemsets, metric='lift', min_threshold=2)
# sort in descending order of lift
rules = rules.sort_values(by='lift', ascending=False)
rules

,antecedents,consequents,antecedent support,consequent support,support,confidence,lift,representativity,leverage,conviction,zhangs_metric,jaccard,certainty,kulczynski
17,frozenset({Croissant}),frozenset({Sweet_bun}),0.100000,0.150000,0.100000,1.000000,6.666667,1.0,0.085000,inf,0.944444,0.666667,1.000000,0.833333
16,frozenset({Sweet_bun}),frozenset({Croissant}),0.150000,0.100000,0.100000,0.666667,6.666667,1.0,0.085000,2.700000,1.000000,0.666667,0.629630,0.833333
67,"frozenset({Dark_bread, Coffee})","frozenset({Veggie_deli_slices, Cucumber})",0.166667,0.100000,0.100000,0.600000,6.000000,1.0,0.083333,2.250000,1.000000,0.600000,0.555556,0.800000
72,"frozenset({Veggie_deli_slices, Cucumber})","frozenset({Dark_bread, Coffee})",0.100000,0.166667,0.100000,1.000000,6.000000,1.0,0.083333,inf,0.925926,0.600000,1.000000,0.800000
55,frozenset({Smoothie}),"frozenset({Dark_bread, Veggie_deli_slices})",0.166667,0.133333,0.116667,0.700000,5.250000,1.0,0.094444,2.888889,0.971429,0.636364,0.653846,0.787500
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
0,frozenset({Juice}),frozenset({Cheese}),0.116667,0.366667,0.100000,0.857143,2.337662,1.0,0.057222,4.433333,0.647799,0.260870,0.774436,0.564935
5,frozenset({Veggie_deli_slices}),frozenset({Dark_bread}),0.233333,0.266667,0.133333,0.571429,2.142857,1.0,0.071111,1.711111,0.695652,0.363636,0.415584,0.535714
4,frozenset({Dark_bread}),frozenset({Veggie_deli_slices}),0.266667,0.233333,0.133333,0.500000,2.142857,1.0,0.071111,1.533333,0.727273,0.363636,0.347826,0.535714
45,"frozenset({Cucumber, Cheese})",frozenset({Dark_bread}),0.183333,0.266667,0.100000,0.545455,2.045455,1.0,0.051111,1.613333,0.625850,0.285714,0.380165,0.460227
46,frozenset({Dark_bread}),"frozenset({Cucumber, Cheese})",0.266667,0.183333,0.100000,0.375000,2.045455,1.0,0.051111,1.306667,0.696970,0.285714,0.234694,0.460227

In [12]:
# create dataframe from dictionary
data = {'cigarettes': [10, 20, 0, 5, 15, 30, 0, 25, 10, 5, 20, 15, 30],
        'genetic_variant': ['A', 'B', 'A', 'C', 'C', 'C', 'A', 'B', 'A', 'B', 'C', 'B', 'A'],
        'disease': [False, False, False, False, True, True, False, False, False, False, True, False, False]}
df = pd.DataFrame(data)
display(df)

    cigarettes genetic_variant  disease
0           10               A    False
1           20               B    False
2            0               A    False
3            5               C    False
4           15               C     True
5           30               C     True
6            0               A    False
7           25               B    False
8           10               A    False
9            5               B    False
10          20               C     True
11          15               B    False
12          30               A    False